id: P008275
initial_creation_type: ocr
source_metadata:
  id: bdr:W21615
  title: ཕོ་བྲང་པོ་ཏ་ལའི་ལོ་རྒྱུས་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    7900b8c7ffba491a963b9c8d1fef8eaf:
      image_group_id: I1GS105527
      title: ''
      volume_number: 1
      total_pages: 132
